version: '3.8'

services:
  # Servicio de autenticación
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    expose:
      - "8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=INFO
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES_IN=3600
      - REFRESH_TOKEN_EXPIRES_IN=2592000
      # Configuración de MySQL
      - USE_IN_MEMORY_DB=false
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=auth_service
    depends_on:
      - mysql
    networks:
      - semantic-search-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Servicio de recolección de datos
  data-harvester:
    build:
      context: ./data-harvester
      dockerfile: Dockerfile
    container_name: data-harvester
    expose:
      - "8002"
    environment:
      - DATA_HARVESTER_HOST=0.0.0.0
      - DATA_HARVESTER_PORT=8002
      - AUTH_SERVICE_URL=http://auth-service:8001
      - DATA_HARVESTER_LOG_LEVEL=INFO
    depends_on:
      - auth-service
    networks:
      - semantic-search-network
    restart: unless-stopped
    volumes:
      - data-harvester-storage:/app/data

  data-storage:
    build:
      context: ./data-storage
      dockerfile: Dockerfile
    container_name: data-storage
    expose:
      - "8003"
    environment:
      - DATA_STORAGE_HOST=0.0.0.0
      - DATA_STORAGE_PORT=8003
      - DATA_STORAGE_ALLOWED_ORIGINS=*
      - DATA_STORAGE_LOG_LEVEL=DEBUG
      - AUTH_SERVICE_URL=http://auth-service:8001
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=data_storage
      - ENABLE_EVENT_PUBLISHING=true
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_EXCHANGE=semantic_search_events
      - AUTH_SERVICE_JWT_SECRET=your-secret-key-change-in-production
      - AUTH_SERVICE_JWT_ALGORITHM=HS256
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - semantic-search-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=data_storage
      - MYSQL_ROOT_HOST=%
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-mysqlx
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - semantic-search-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  # RabbitMQ para mensajería entre servicios
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto AMQP
      - "15672:15672" # Puerto interfaz de administración
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - semantic-search-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-processor:
    build:
      context: ./data-processor
      dockerfile: Dockerfile
    container_name: data-processor
    expose:
      - "8004"
    environment:
      - DATA_PROCESSOR_HOST=0.0.0.0
      - DATA_PROCESSOR_PORT=8004
      - AUTH_SERVICE_URL=http://auth-service:8001
      - DATA_HARVESTER_URL=http://data-harvester:8002
      - DATA_STORAGE_URL=http://data-storage:8003
      - DATA_PROCESSOR_LOG_LEVEL=INFO
    depends_on:
      - auth-service
      - data-harvester
      - data-storage
    networks:
      - semantic-search-network
    restart: unless-stopped
    volumes:
      - data-processor-storage:/app/data

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    volumes:
      - chromadb-data:/chroma/chroma
    expose:
      - "8000"
    environment:
      - ALLOW_RESET=True
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    networks:
      - semantic-search-network
    restart: unless-stopped

  # Servicio de embeddings
  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    container_name: embedding-service
    expose:
      - "8005"
    environment:
      - EMBEDDING_SERVICE_HOST=0.0.0.0
      - EMBEDDING_SERVICE_PORT=8005
      - EMBEDDING_SERVICE_ALLOWED_ORIGINS=*
      - EMBEDDING_SERVICE_LOG_LEVEL=INFO
      - AUTH_SERVICE_URL=http://auth-service:8001
      - DATA_STORAGE_URL=http://data-storage:8003
      - EMBEDDING_SERVICE_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - VECTOR_DB_TYPE=chromadb
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - CHROMADB_PERSISTENCE_PATH=/app/storage/chroma
      - CACHE_ENABLED=true
      - CACHE_TTL=3600
      - BATCH_SIZE=32
      - REQUEST_TIMEOUT=60
      - EVENT_CONSUMER_ENABLED=true
      - EVENT_CONSUMER_TYPE=rabbitmq
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_EXCHANGE=semantic_search_events
      - RABBITMQ_QUEUE=embedding_service_events
    depends_on:
      - auth-service
      - data-storage
      - chromadb
      - rabbitmq
    networks:
      - semantic-search-network
    restart: unless-stopped
    volumes:
      - embedding-service-storage:/app/storage

  # Servicio de búsqueda
  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    container_name: search-service
    expose:
      - "8006"
    environment:
      - SEARCH_SERVICE_HOST=0.0.0.0
      - SEARCH_SERVICE_PORT=8006
      - AUTH_SERVICE_URL=http://auth-service:8001
      - EMBEDDING_SERVICE_URL=http://embedding-service:8005
      - SEARCH_SERVICE_LOG_LEVEL=INFO
    depends_on:
      - auth-service
      - embedding-service
    networks:
      - semantic-search-network
    restart: unless-stopped
    volumes:
      - search-service-storage:/app/data

  # API Gateway (Orquestador)
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    ports:
      - "8000:8000"
    environment:
      - API_GATEWAY_HOST=0.0.0.0
      - API_GATEWAY_PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:8001
      - DATA_HARVESTER_URL=http://data-harvester:8002
      - DATA_STORAGE_URL=http://data-storage:8003
      - DATA_PROCESSOR_URL=http://data-processor:8004
      - EMBEDDING_SERVICE_URL=http://embedding-service:8005
      - SEARCH_SERVICE_URL=http://search-service:8006
      - API_GATEWAY_LOG_LEVEL=INFO
    depends_on:
      - auth-service
      - data-harvester
      - data-storage
      - data-processor
      - embedding-service
      - search-service
    networks:
      - semantic-search-network
    restart: unless-stopped


networks:
  semantic-search-network:
    driver: bridge

volumes:
  data-harvester-storage:
  data-processor-storage:
  embedding-service-storage:
  search-service-storage:
  mysql-data:
  chromadb-data:
  rabbitmq-data: 